services:
  # Node.js 애플리케이션 (개발 모드)
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: pbt-lms-app-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "9229:9229" # Node.js 디버깅 포트
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=magic7
      - DB_USER=magic7
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DIALECT=mysql
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=7d
      - SESSION_SECRET=${SESSION_SECRET}
      - MAX_FILE_SIZE=10485760
      - UPLOAD_DIR=./uploads
      - CLIENT_URL=http://localhost:3000
      - SWAGGER_ENABLED=true
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      # 소스 코드를 볼륨으로 마운트 (개발 중 코드 변경 시 즉시 반영)
      - ./src:/app/src:cached
      - ./public:/app/public:cached
      - ./package.json:/app/package.json:ro
      - ./server.js:/app/server.js:cached
      - ./uploads:/app/uploads
      - ./tmp:/app/tmp
      - ./logs:/app/logs
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - pbt-network-dev
    command: ["npm", "start"] # 개발 모드에서 node 사용

  # MySQL 데이터베이스 (개발용)
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    container_name: pbt-lms-mysql-dev
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=magic7
      - MYSQL_USER=magic7
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - pbt-network-dev
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 60s

  # Redis (개발용)
  redis:
    image: redis:7-alpine
    container_name: pbt-lms-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - pbt-network-dev
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # Adminer (데이터베이스 관리 도구)
  adminer:
    image: adminer:latest
    container_name: pbt-lms-adminer-dev
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
      - ADMINER_DESIGN=pepa-linha
    depends_on:
      - mysql
    networks:
      - pbt-network-dev

  # MailHog (개발용 메일 서버)
  mailhog:
    image: mailhog/mailhog:latest
    platform: linux/amd64
    container_name: pbt-lms-mailhog-dev
    restart: unless-stopped
    ports:
      - "1025:1025" # SMTP 포트
      - "8025:8025" # 웹 UI 포트
    networks:
      - pbt-network-dev

volumes:
  mysql_data_dev:
    driver: local
  redis_data_dev:
    driver: local

networks:
  pbt-network-dev:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
